### PR TITLE
Reversable wheel

### PR DESCRIPTION
**Pull request by JJK801**
Hi !

In order to make wheel usable for trackpads, this PR adds a `reversed` option that allow to easily switch to a natural scrolling.

I added the corresponding tests and docs.

Thanks

### CODE REVIEW

**Comment by dbismut** [comment]
Salut @JJK801, thanks for the PR. A few questions:

- you wrote touchscreens in your message, are some touchscreens responding to onWheel events?

- isn’t it simpler to just multiply the offset / movement by `-1` in userland?

- I might be missing something but why do you need to write reversed in the state? Wouldn’t reading the config suffice?

**Comment by JJK801** [comment]
Hi @dbismut,

> * you wrote touchscreens in your message, are some touchscreens responding to onWheel events?

My bad, i didn't try on a touchscreen and was cnvicted that two touches move simulate a wheel, i will change that.

> * isn’t it simpler to just multiply the offset / movement by `-1` in userland?

Obviously, that's what i expected first, but when using `initial` config (beacause of the aggregate), the behavior become strange and necessitate many computations to be corrected in the userland.

> * I might be missing something but why do you need to write reversed in the state? Wouldn’t reading the config suffice?

i think it's always useful to retrieve the exact current behavior in the state instead of guessing it (that could be done by comparing event delta against the computed delta, but it's not obvious for everyone)

**Comment by dbismut** [comment]
@JJK801 can you please open a sandbox showing the intricate logic that inverting the wheel value generates? Here is a quick sandbox with initial that doesn't seem that complicated to me ;)

https://codesandbox.io/s/withered-architecture-rggri

> i think it's always useful to retrieve the exact current behavior in the state instead of guessing it

If it's a config option that you're passing why would you need to read it from state?

**Comment by JJK801** [comment]
> @JJK801 can you please open a sandbox showing the intricate logic that inverting the wheel value generates? Here is a quick sandbox with initial that doesn't seem that complicated to me ;)
> 
> https://codesandbox.io/s/withered-architecture-rggri

Here is my use case, simply negate the value isn't a fair way in this case, because it will impact any computation, any user input, etc... What i need is a way to set the right value straight to my state from the handler.

https://codesandbox.io/s/zen-river-lekd9

> 
> > i think it's always useful to retrieve the exact current behavior in the state instead of guessing it
> 
> If it's a config option that you're passing why would you need to read it from state?

I don't need it in my use case but when using re-usable handlers, it's a good practice imo to not depends the context.

**Comment by dbismut** [comment]
If you set initial to `-origin.y` I think it should work as you expect?
What is `_isReversed?`?

Sorry if I'm missing the point but I want to keep the API surface as light as possible (it's already pretty large for such a small lib).

**Comment by JJK801** [comment]
> If you set initial to `-origin.y` I think it should work as you expect?

Nope, i tried many combinations, but the internal work make it quite hard to fix the problem.

> What is `_isReversed`?

i've added it thinking that it was a convention, but i forgot to remove it.

> Sorry if I'm missing the point but I want to keep the API surface as light as possible (it's already pretty large for such a small lib).

No problem, you're totally right and it can be me that missed something :)

**Comment by dbismut** [comment]
I'm closing this since I'm not convinced this is actually necessary. If any one finds it useful, please let me know and I'll reconsider.

**Pull request closed without merging**
